### ISSUE TITLE
bunlar private olabilir

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/oguzhan_onal_covid_onboarding#1]
https://github.com/VBT-FlutterCamp/oguzhan_onal_covid_onboarding/blob/bd079f9c26af96257950665f8e7a8eae3a719f7d/lib/feature/onboard/view/onboard_screen_view.dart#L68

double _radius=20.0;
gibi yada kartal paketi :)

**Comment by oguzhannonal** [comment]
düzeltildi teşekkürler.
