### ISSUE TITLE
Next lower case olmalı

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/oguzhan_onal_covid_onboarding#2]
https://github.com/VBT-FlutterCamp/oguzhan_onal_covid_onboarding/blob/bd079f9c26af96257950665f8e7a8eae3a719f7d/lib/product/compenents/app_string.dart#L3

klasör yapın ve kodun temiz eline sağlık

**Comment by oguzhannonal** [comment]
teşekkür ederim lower case yaptım
