### ISSUE TITLE
static variable

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/oguzhan_onal_covid_onboarding#4]
Sayfa içerisinde static degisken bırakmadıgımız için ve 2 farklı yerde 1 amacına yönelik kullandıgımızdan dolayı 
int _lastPageValue =1 ; şeklinde tanımlayıp çağırabiliriz
https://github.com/VBT-FlutterCamp/oguzhan_onal_covid_onboarding/blob/596a479af8aea4f96ecf7132790146f15090e584/lib/feature/onboard/view/onboard_screen_view.dart#L126

**Comment by oguzhannonal** [comment]
Hocam ekstra bir sayfa ekleme durumunda sıkıntı olmaz mı yani models.lenght daha iyi bir çözüm değil mi ?

**Comment by oguzhannonal** [comment]
Düzeltildi sağolun hocam.
