### ISSUE TITLE
Private

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/oguzhan_onal_covid_onboarding#5]
Burada private yapamızdaki amaç nedir? Bu sınıf genel bir text sınıfı oldugu için dısarıdan rahatlıkla çekmeliyiz 
https://github.com/VBT-FlutterCamp/oguzhan_onal_covid_onboarding/blob/596a479af8aea4f96ecf7132790146f15090e584/lib/product/compenents/app_string.dart#L4

**Comment by oguzhannonal** [comment]
Düzeltildi sağolun hocam.
